services:
  db:
    image: postgres:17.4-bookworm
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
    command: npm run db:migrate
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
    depends_on:
      migrator:
        condition: service_completed_successfully
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge